steps:
  - name: 'python'
    entrypoint: 'bash'
    args: ['-c', 'pip install -r requirements.txt && pip install pytest flake8 && flake8 app.py && pytest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/cicd-234/cicd/flask-app:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/cicd-234/cicd/flask-app:latest']
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - deploy
      - releases
      - create
      - release-$BUILD_ID
      - --delivery-pipeline=cicd-pipeline
      - --region=us-central1
      - --images=flask-app=us-central1-docker.pkg.dev/cicd-234/cicd/flask-app:latest

images:
  - 'us-central1-docker.pkg.dev/cicd-234/cicd/flask-app:latest'

options:
  logging: CLOUD_LOGGING_ONLY
