apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: flask-app
build:
  artifacts:
  - image: us-central1-docker.pkg.dev/cicd-234/cicd/flask-app
deploy:
  cloudrun:
    projectId: cicd-234
    region: us-central1
    service: flask-app
